# Disable sudo to enable containerization
sudo: false

# Setup Go language support
language: go

## TODO: If we ever get Clobber support for building on linux,
##       we might want to run this on BOTH "linux" and "osx" targets
# Run builds specifically on macOS
os: osx

# Setup global environment variables
env:
  - GO111MODULE=on
  - TEST_COMMAND="go test -race -coverprofile=coverage.txt -covermode=atomic ./..."

# Setup Go version specific configurations
matrix:
  include:
  - go: master
  - go: 1.11.x

# Setup caching
cache:
  directories:
    - $HOME/.clobber/opt

# Install dependencies
install:
  - mkdir -p $GOPATH/{bin,pkg,src}
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  #- dep ensure
  - go get
  ## TODO: On Go versions <1.11, run "go mod vendor"?

# Run tests and generate code coverage
script:
  - eval $TEST_COMMAND
  - .scripts/build.sh
  - ./clobber --version
  ## TODO: Re-enable once the "go mod" migration is done
  #- brew tap Dids/brewery
  #- brew install clobber --HEAD
  #- clobber --version

# Upload code coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
