language: go

os: osx

matrix:
  include:
  #- go: master
  #  script: make deps build test install version
  - go: 1.11.x
    script: make deps build test install version
  - go: 1.10.x
    script: make deps build test install version EXTRA_FLAGS=
  - go: 1.9.x
    script: make deps build install version EXTRA_FLAGS=

env:
  - GO111MODULE=on

install: true

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.clobber/opt
