# Disable sudo to enable containerization
sudo: false

# Setup Go language support
language: go

# Test against multiple versions of Go
go:
  - 1.10.x
  - 1.9.x
  - 1.8.x
  - master

# Setup caching
cache:
  directories:
    ## TODO: We might want to clean things up before caching..
    - $HOME/.clobber/opt

# Install dependencies
before_install:
  - go get -t -v ./...

# Run tests and generate code coverage
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

# Upload code coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
