language: go

os: osx

matrix:
  include:
  - go: master
    script: make clean deps build test install version
  - go: 1.11.x
    script: make clean deps build test install version
  - go: 1.10.x
    script: make clean deps build test-no-vendor install version
  - go: 1.9.x
    script: make clean deps build install version

env:
  - GO111MODULE=on

install: true

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.clobber/opt
