language: go

os: osx

matrix:
  fast_finish: true
  allow_failures:
    #- go: master
    - go: tip
  include:
  #- go: master
    #script: make deps build test install version
  - go: tip
    #script: make deps build test install version
    script:
      - make deps
      - make build
      - make test
      - make install
      - make version
  - go: 1.11.x
    #script: make deps build test install version
    script:
      - make deps
      - make build
      - make test
      - make install
      - make version
  - go: 1.10.x
    #script: make deps build test install version EXTRA_FLAGS=
    script:
      - make deps EXTRA_FLAGS=
      - make build EXTRA_FLAGS=
      - make test EXTRA_FLAGS=
      - make install EXTRA_FLAGS=
      - make version EXTRA_FLAGS=
  - go: 1.9.x
    #script: make deps build install version EXTRA_FLAGS=
    script:
      - make deps EXTRA_FLAGS=
      - make build EXTRA_FLAGS=
      - make test EXTRA_FLAGS=
      - make install EXTRA_FLAGS=
      - make version EXTRA_FLAGS=

env:
  - GO111MODULE=on

install: true

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.clobber/opt
    - $GOPATH
    #- $GOPATH/bin
