language: go

os: osx

matrix:
  include:
  - go: master
    script: go test -v -mod=vendor -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go: 1.11.x
    script: go test -v -mod=vendor -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go: 1.10.x
    script: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go: 1.9.x

env:
  - GO111MODULE=on

install: true

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.clobber/opt
