language: go

os: osx

matrix:
  include:
  - go: master
    script: make clean deps packr-build test packr-install version
  - go: 1.11.x
    script: make clean deps packr-build test packr-install version
  - go: 1.10.x
    script: make clean deps packr-build test instpackr-installall version EXTRA_FLAGS=
  - go: 1.9.x
    script: make clean deps packr-build packr-install version EXTRA_FLAGS=

env:
  - GO111MODULE=on

install: true

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.clobber/opt
